### ISSUE TITLE
Doesn't work on Ubuntu 22.04.1 

### ISSUE THREAD

**Issue by stschirky** [LordAmit/Brightness#212] opened 2022-08-22 16:54 UTC
I updated to ubuntu 22.04.1 LTS and can't get the tool to work anymore. The GUI works fine, it recognizes my screens, but it doesn't adjust the brightness anymore.

**Comment by LordAmit** [comment] 2022-08-23 22:10
wayland?

**Comment by stschirky** [comment] 2022-08-24 05:57
seems so

**Comment by apandada1** [comment] 2022-08-24 13:09
Use X.Org instead. The backend (xrandr) used by this tool does not work with Wayland.

Duplicate of #189

**Closed** 2022-08-25 00:53 UTC
