### ISSUE TITLE
Update README.md to add  -  pip3 install pyqt5-tools

### ISSUE THREAD

**Issue by rlogwood** [LordAmit/Brightness#188] opened 2021-03-31 00:26 UTC
**Describe the bug**
Following the installation docs does not provide a working install. Users must also install Qt bindings. 

Update the README.md to include instructions for installing Qt bindings, for example: `pip3 install pyqt5-tools`

The docs say to run `pip3 install qtpy`, however, this assumes you already have the Qt bindings installed already. 

```
$ pip3 show qtpy
Name: QtPy
Version: 1.9.0
Summary: Provides an abstraction layer on top of the various Qt bindings (PyQt5, PyQt4 and PySide) and additional custom QWidgets.
Home-page: https://github.com/spyder-ide/qtpy
Author: Colin Duquesnoy, The Spyder Development Team
Author-email: goanpeca@gmail.com
License: MIT
```
**With the bindings missing the following error occurs:**
```sh
$ python3 src/init.py
Traceback (most recent call last):
  File "/home/(username)/.pyenv/versions/3.9.2/lib/python3.9/site-packages/qtpy/__init__.py", line 204, in <module>
    from PySide import __version__ as PYSIDE_VERSION  # analysis:ignore
ModuleNotFoundError: No module named 'PySide'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/(username)/Downloads/Brightness/Brightness-master/src/init.py", line 22, in <module>
    from qtpy import QtGui, QtCore, QtWidgets
  File "/home/(username)/.pyenv/versions/3.9.2/lib/python3.9/site-packages/qtpy/__init__.py", line 210, in <module>
    raise PythonQtError('No Qt bindings could be found')
qtpy.PythonQtError: No Qt bindings could be found
```

**To Reproduce**
1. My system is a fresh Ubuntu 20.04.2 LTS install
2. Using linuxbrew (homebrew) to install pyenv and python versions
3. `brew install pyenv` [see pyenv formulae](https://formulae.brew.sh/formula/pyenv)
2. `pyenv install 3.9.2`  # (currently latest version of python3 as of this writing)
2. `pyenv local 3.9.2` 
3. `pyenv which pip3`
4. `pyenv which python3`
5. `pip3 install qtpy`
6. download the master.zip 
7. unzip Brightness-master.zip
8. cd Brightness-master
9. `python3 src/init.py`
10. See above error listing: **With the bindings missing the following error occurs**
11. **to fix the problem `pip3 install pyqt5-tools`**
12. `python3 src/init.py`
13. this time it will work :) 

**Expected behavior**
- Expect application to start successfully with `python3 src/init.py`

**Desktop (please complete the following information):**
 - Ubuntu 20.04.2 LTS
 - Firefox latest

**Comment by LordAmit** [comment] 2021-03-31 02:14
@rlogwood thanks for the detailed issue! When we changed the instructions for `QtPy` (this is a _very_ recent change, btw).

The issue is that some systems may come with preinstalled PySide (or equivalent), and some systems don't. If it comes with such, installing it again may mess up existing Qt for Python bindings (or eat up space anyway). That's the reason we went for the wrapper route.

But, the previous documentation did not adequately described this, which is why we had somewhat confusing instructions.

I tried to make it more explicit by updating the `Readme`-->`Manual Installation`. Can you please take a look and let me know if this clarifies things better?  

also, tagging @apandada1  - will our changes break the installation packages (deb/ppa etc.) in case a system does not come with pre-installed PySide/equivalent?

**Comment by apandada1** [comment] 2021-03-31 04:05
I have not updated the PPA yet, as it would require some testing.

I tested the source in various OS and DEs, but did not encounter this issue. I am not familiar to homebrew. I installed `python3-qtpy` with `apt`, and that worked for me in Ubuntu based systems.

**Comment by rlogwood** [comment] 2021-03-31 06:24
Hi @apandada1, 

It works fine doing that. 

**The steps I followed are:** 
1. Switched my python3 version to the default one installed with Ubuntu ( v3.8.5), using the command: `pyenv local system`, 
2. Ran `sudo apt install python3-qtpy` (no need to uninstall from `pip` as `pyenv` lets you manage multiple installs and switch back to the system version as needed). 
3. Successfully executed `python3 src/init.py`

**Please NOTE:** Even though the app is running ok, there is a missing icon error, which I just noticed:
```sh
qt.svg: Cannot open file '/home/(username)/Downloads/Brightness/Brightness-master/icons/brightness-controller.svg', because: No such file or directory
```
* * * 
### suggested resolution for README.md update:
`pyenv` provides  a convenient way to manage multiple python installs. Maybe you/we could augment the README.md to show  `pip3 install pyqt5-tools` as an alternative to `sudo apt install python3-qtpy` for users of `pyenv`.

**Comment by apandada1** [comment] 2021-03-31 06:42
I cannot reproduce the missing icon warning when running from source. It will probably be fixed in apt install. I will see.

**Comment by LordAmit** [comment] 2021-03-31 12:40
Giving specialized instructions regarding `pyenv` or similar is a slippery slope, considering the possibilities of customizations linux allows. 

Since we already discuss about installing `QtPy` being a wrapper, give an example using `PySide2`, and explain further about it under the Requirements - these general descriptions should be sufficient to run Brightness controller in system environment, and by extension the customizations. 👯‍♂️

**Comment by rlogwood** [comment] 2021-03-31 13:01
Hi @LordAmit, I appreciate what you are saying, it's impossible to cover all the scenarios.  Reading the [Requirements](https://github.com/LordAmit/Brightness#requirements) I can then try to translate those myself with google. For example when I google `homebrew python3-qtpy` I can find a [formulae for Python bindings for v6 of Qt](https://formulae.brew.sh/formula/pyqt).

**Comment by LordAmit** [comment] 2021-04-07 15:58
Will keep this in mind when updating the redme. Thank you for the feedback and explaining your perspective!

**Closed by LordAmit** 2021-04-07 15:58 UTC
