### ISSUE TITLE
App does not work on Ubuntu 21.04 hirsute

### ISSUE THREAD

**Issue by Salman-Asif** [LordAmit/Brightness#198] opened 2021-11-18 20:31 UTC
Installed the app through CLI (Commands mentioned in the README.md)
On opening the Brightness Controller app and adjusting the brightness , nothing seems to happen.
Neither increase nor decrease happens. No settings including RGB changes seems to take affect.

**Comment by apandada1** [comment] 2021-11-18 20:37
Possible duplicate of https://github.com/LordAmit/Brightness/issues/189
Switch to X.Org.

**Comment by Salman-Asif** [comment] 2021-11-18 20:55
Yes I've read the other issue. I believe this was raised before and it's a duplicate. Closed the issue now.
Thanks :)

**Closed** 2021-11-18 20:54 UTC
